my_todo = open('test/todo.txt', 'r', encoding='UTF8')
lines = my_todo.readlines()
print(lines)
my_todo.close()
print("----------------------------------------------------")
my_todo = open('test/todo.txt', 'r', encoding='UTF8')
first_line = my_todo.readline()
second_line = my_todo.readline()
third_line = my_todo.readline()
print(f"1: {first_line}2: {second_line}3: {third_line}")
my_todo.close()